security: 
  basic: 
    enable: false
server: 
  context-path: /auth
  port: 8081
spring: 
  application: 
    name: oauth2-test
  datasource: 
    password: admin
    url: "jdbc:mysql://localhost:3306/rentdb"
    username: admin
  jpa: 
    hibernate: 
      ddl-auto: none
  profiles: 
    active: develop
